# Generated by Django 4.2.1 on 2023-06-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
