# Generated by Django 4.2.1 on 2023-07-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderproduct_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('out for shipping', 'out for shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='In Progress', max_length=50),
        ),
    ]
