# Generated by Django 4.2.1 on 2023-06-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
