# Generated by Django 4.2.1 on 2023-06-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_color_price_size_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
    ]
